### ISSUE TITLE
ERROR_LOGIN_PARAMETERS_MISSING

### ISSUE THREAD

**Issue by reinethernal** [ticgal/gappessentials#11]
<p><a href=\\\"https://github.com/ticgal/gappessentials/issues/11\\\">https://github.com/ticgal/gappessentials/issues/11</a></p><p>Trying to connect to my glpi server. I configure the connection via https, enter the server address, (my.glpi.server) try to connect, writes: login password or authentication token is missing; viewing the documentation in your browser in <a href=\\\"https://my.glpi.server/restapi.php/\\\">https://my.glpi.server/restapi.php/</a> # ERROR_LOGIN_PARAMETERS_MISSING</p><p><br />Created by reinethernal</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_2180' rel='nofollow'>2180</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Beiro Óscar (14)</blockquote>

**Comment by OscarBeiro** [comment]
Hi @Reinethernal,

A quick google search would have returned a KB article :)
https://tic.gal/en/error_app_token_parameters_missing-connecting-to-glpi-api/

Regards,

**Comment by reinethernal** [comment]
Tried to do in a such way - still not working. But i haven't configured ip access rang, because i need to access from different places.

**Comment by OscarBeiro** [comment]
If no IP is selected, no restriction is applied.
Could you post the API Client screen?

**Comment by reinethernal** [comment]
![image](https://user-images.githubusercontent.com/35932698/65680505-c1d53080-e05f-11e9-8300-aa5be186c3da.png)
![image](https://user-images.githubusercontent.com/35932698/65680588-eb8e5780-e05f-11e9-8a84-025209538a7f.png)

**Comment by OscarBeiro** [comment]
It looks OK.

Could you show the Historical log from the API Client. Just to check if there are any additional informations that could help us debugging this.

I assume you can connect to the demo server.

**Comment by reinethernal** [comment]
![image](https://user-images.githubusercontent.com/35932698/65681106-f5fd2100-e060-11e9-85ed-2eedf79fd427.png)

**Comment by reinethernal** [comment]
> I assume you can connect to the demo server.

Yes, i can connect to the test server. Seems that i'm doing something wrong, but can's find - what :)

**Comment by OscarBeiro** [comment]
We will do our best to help you, but apparently everything is OK, so it has to be something on your side.

If we think of something we'll get back to you.

**Comment by reinethernal** [comment]
@OscarBeiro thank you! One more question. Any ideas how can i check connection to the api?

**Comment by OscarBeiro** [comment]
Hi @reinethernal,

API documentation is the best source for this.
Please try to login using curl.
https://github.com/glpi-project/glpi/blob/master/apirest.md#init-session

Regards,

**Comment by reinethernal** [comment]
Hi!
Tried to init session with documentation at https://github.com/glpi-project/glpi/blob/master/apirest.md#init-session Not worked. Tried to connect by 

`app_token=
user_token=

curl -X GET -H 'Content-Type: application/json' \
 'https://path/to/glpi/apirest.php/initSession?Content-Type=%20application/json&app_token='$app_token'&user_token='$user_token`

It worked. But i needed to log in via token auth... (((

**Comment by reinethernal** [comment]
I use ldap authentication

**Comment by reinethernal** [comment]
Tried that way-no responce. I'll check it

**Comment by reinethernal** [comment]
tried two accaounts - not working (with your example). 
Tried again with this variant  in one bash script 

> `app_token=
> user_token=

> curl` -X GET -H 'Content-Type: application/json'
> 'https://path/to/glpi/apirest.php/initSession?Content-Type=%20application/json&app_token='$app_token'&user_token='$user_token`

and connected.

**Comment by OscarBeiro** [comment]
Hi,

You seem to be using **&app_token='$app_token'**
In your previous screenshots, you had this parameter empty, which is the only API Client configuration supported .
 
Either way, this seems to be something on your side, since demo app works. Gapp is free, we cannot support each particular setup. 
If you want us to support this specific instalation, please contact us at hello @ ticgal . com

For future Gapp issues please use https://github.com/ticgal/gapp . This one is for Gapp Essentials

Regards,

**Comment by reinethernal** [comment]
i used empty app_token= and user_token= not to store them at github

**Comment by reinethernal** [comment]
@OscarBeiro still not working. tried different ways. tunneled traffic right from server, but nothung changes. same error

**Comment by OscarBeiro** [comment]
This is issue is not related to Gapp Essentials 
This  other one is the place to open tickets regarding Gapp: https://github.com/ticgal/gapp
Said that, the issue is related to your particular instalation. We cannot support it.
If you want professional support please contact us on https://tic.gal/glpi

**Comment by reinethernal** [comment]
And again. curl requests with basic auth work fine. App could not connect.
