### ISSUE TITLE
Gapp Essentials 9.3 + 9.5 support

### ISSUE THREAD

**Issue by gitsyncuser** [ticgal/gappessentials#13]
<p>Once it's done, <del>we support GLPI 9.3 and</del> (dropped) see if it works on 9.5, so we can release a new version: 1.1.0.</p><p>You have to ask Pedro if it will affect the version change in your check of the plugins.</p><p>Maybe we could change this value with Firebase remote config.</p><p>If there is a new version of Gapp Essentials or any other. We can force the upgrade without having to release a new version. What do you think?</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_2372' rel='nofollow'>2372</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Beiro Óscar (14)</blockquote>

**Comment by gitsyncuser** [comment]
<p>Orixinal privado :)</p><p>Xa que está feito, soportamos GLPI 9.3 e vemos se funciona en 9.5, para sacar así unha versión nova: 1.1.0.</p><p>Hai que preguntarlle a Pedro se afectará o cambio de versión no seu check dos plugins.</p><p>Se cadra este sería un bo campo para cambiar con Firebase remote config.</p><p>Se hai nova versión de Gapp Essentials ou calquera outro. Que poidamos forzar a actualización sin ter que liberar unha nova versión.</p><p>Que vos parece?</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Beiro Óscar (14)</blockquote>

**Comment by OscarBeiro** [comment]
Been released GLPI 9.5, we will focus our efforts on supporting 9.5 rather than an old, unsupported GLPI version.

**Comment by OscarBeiro** [comment]
Done on https://github.com/ticgal/gappessentials/pull/16
