### ISSUE TITLE
add multi selection of files in the document upload

### ISSUE THREAD

**Issue by da-sti** [ticgal/gappessentials#14]
<p><a href="https://github.com/ticgal/gappessentials/issues/14">https://github.com/ticgal/gappessentials/issues/14</a></p><p>Hi !</p><p>I just tried the app and it's very nice, congratulations and thank you for putting that out there, opensource.</p><p>When uploading multiple documents the process goes like this : processing > + > ';documents'; > + > ';files'; > select in android file list</p><p>at this last selection it's possible to select only one file at the time, could it be possible to select several files in one action ?</p><p>Thanks DS</p><p><br />Created by da-sti</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_2563' rel='nofollow'>2563</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Beiro Óscar</blockquote>

**Comment by OscarBeiro** [comment]
Hi,
Thanks for your feedback. This is a great idea and is already on the roadmap.

In the future, please leave this repository for Gapp Essentials issues, and use https://github.com/ticgal/gapp for Gapp related ones.
Thanks

Regards,

**Comment by OscarBeiro** [comment]
This is a https://github.com/ticgal/gapp feature.
