### ISSUE TITLE
Task privacy

### ISSUE THREAD

**Issue by buggzbeny** [ticgal/gappessentials#15]
<p><a href="https://github.com/ticgal/gappessentials/issues/15">https://github.com/ticgal/gappessentials/issues/15</a></p><p>Hello,</p><p>First want to thank you for this app. Really good project ;)</p><p>When we add a task on an open ticket through native GLPI website, i put tis status private by default.<br />When i put a task through Gapp status can be changed at the input, i had to re open the task to put it private, or notification is already gone !</p><p>Can you add the possibility to select the status private at the creation of the task / followup without re open it to change the status ?</p><p>thanks.</p><p><br />Created by buggzbeny</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_3130' rel='nofollow'>3130</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by gitsyncuser** [comment]
<p><p dir=\"ltr\">Qué versión usa? Porque eso es así en la 1.1</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Pedro Muñoz</blockquote>

**Comment by buggzbeny** [comment]
![image](https://user-images.githubusercontent.com/45596518/77738414-186ff700-7010-11ea-8384-8d8d79b3c679.png)

Here is the version we use

**Comment by OscarBeiro** [comment]
Hi @buggzbeny,
Thanks for you kind words.
Sorry about my colleague previous comment. It was supposed to be internal :)

Upcoming Gapp 1.1.0 will use same setting as GLPI for Followups and Tasks regarding privacy.

Follow us on twitter for updates,

**Comment by buggzbeny** [comment]
Hello,
My mistake. We can chose as you say but can we put a default value for all the technicians like on the web version ?
I want to put it private by default for all.

Thanks

**Comment by OscarBeiro** [comment]
Hi @buggzbeny,

As I told you before this feature will be available for upcoming Gapp 1.1. 
The setting would be taken from GLPI setup.

Please open future bugs or feature requests for Gapp here: https://github.com/ticgal/gapp/issues

Thanks,
