### ISSUE TITLE
The install plugin button is missing

### ISSUE THREAD

**Issue by kofe88** [ticgal/gappessentials#17]
<p><a href="https://github.com/ticgal/gappessentials/issues/17">https://github.com/ticgal/gappessentials/issues/17</a></p><p>GLPI 9.5.2 gappessentials 1.2.0 Copy folder gappessentials to plugins directory. <img src="https://user-images.githubusercontent.com/16879167/99358311-634fbf00-28be-11eb-9050-ba964f8301c9.JPG" alt="gapp" /></p><p><br />Created by kofe88</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_4508' rel='nofollow'>4508</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by OscarBeiro** [comment]
Hi,
Gapp Essentials only supports marketplace installation.
You can move the plugin from plugins to marketplace folder in order to install it.

I have added a note to the Readme.md file and we will add a warning in the next release.

Please test it, and report back.
Don't forget to add the fifth star at Google Play :)

**Comment by kofe88** [comment]
Installed via the marketplace, the system says that installed. 
![image](https://user-images.githubusercontent.com/16879167/99379461-c13dd000-28d9-11eb-9510-6932ecb58b6a.png)
![image](https://user-images.githubusercontent.com/16879167/99379522-dadf1780-28d9-11eb-8c13-0562563abb01.png)
But in the application "GAPP" writes that it is not installed.
![image](https://user-images.githubusercontent.com/16879167/99380551-2c3bd680-28db-11eb-900f-14c3e9b9948e.png)

**Comment by gitsyncuser** [comment]
<p><p dir=\"ltr\">Did you remove Gapp Essentials folder from plugins folder? </p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by kofe88** [comment]
> Did you remove Gapp Essentials folder from plugins folder?
> 
> > Created with [GitSync](https://tic.gal) in GLPI by Óscar Beiro
Yes, of course.
![image](https://user-images.githubusercontent.com/16879167/99384878-25b05d80-28e1-11eb-83dc-80ba792711bb.png)

**Comment by OscarBeiro** [comment]
Hi,

Please, download GAT version for GLPI 9.5: https://tic.gal/en/project/gat/

And send us the report.

You can also disable every plugin. There must be something weird in your installation.

**Comment by kofe88** [comment]
> Hi,
> 
> Please, download GAT version for GLPI 9.5: https://tic.gal/en/project/gat/
> 
> And send us the report.
> 
> You can also disable every plugin. There must be something weird in your installation.

I make new clean install of GLPI 9.5.2 and install only gapessentials from marketplace and have same error.
[support.sz.ru_2020-11-18_01-05-40.txt](https://github.com/ticgal/gappessentials/files/5556546/support.sz.ru_2020-11-18_01-05-40.txt)

**Comment by SEMagarinos** [comment]
Hi!!, I happen the same thing, do you need to make me do some extra tests so that it can work?

**Comment by kofe88** [comment]
> Hi!!, I happen the same thing, do you need to make me do some extra tests so that it can work?

Hello. It never worked for me.

**Comment by OscarBeiro** [comment]
Hi,
Sorry about the late reply.
We finally found the issue. Some "not very documented" :) change with the API, that seems to work on updated machines, but clean not on clean GLPI installs. 
We are releasing a new version as soon as we test it.
Regards,

**Comment by xacobofg** [comment]
Hi,
Can you test #19  ?

**Comment by OscarBeiro** [comment]
Hi,
We have finally been able to reproduce the error.
Gapp Essentials **MUST** be installed in the marketplace folder. 
**Please remove any Gapp Essentials from the plugins folder to avoid this problem.**
You don't need to install it using the Marketplace feature (it is recommended, though).
Regards,
