### ISSUE TITLE
[question] Delete `1.4.0` tag

### ISSUE THREAD

**Issue by AKorezin** [ticgal/gappessentials#28]
<p><a href="https://github.com/ticgal/gappessentials/issues/28">https://github.com/ticgal/gappessentials/issues/28</a></p><p><a href="https://github.com/ticgal/gappessentials/issues/28">https://github.com/ticgal/gappessentials/issues/28</a></p><ol><li>Is <code>1.4.0</code> official release compatible with <code>10.0</code> or it's just a <em>pre-release</em>?</li><li>Will there be more releases after <code>1.3.0</code> for <code>9.5</code>?</li></ol><p><br />Created by AKorezin</p><p>n</p><blockquote><div>GLPI ticket number: <a href="https://xes.ticgal.com/index.php?redirect=ticket_9490" rel="nofollow">9490</a><br />Created with <a href="https://tic.gal">GitSync</a> in GLPI by Óscar Beiro</div></blockquote>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_9490' rel='nofollow'>9490</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by AKorezin** [comment]
@OscarBeiro is it possible to remove 1.4.0 if it was a mistake?

**Comment by OscarBeiro** [comment]
I've never done that, but I suppose we could do it.
I'm curious, why is it so important to you?

**Comment by AKorezin** [comment]
@OscarBeiro I use automation tools to monitor updates. BTW I can limit the version range if I have to, but I'd rather prefer to report or ask a question in upstream.
I think that there are other people who can possibly encounter this problem, so I have a proposition to remove a tag.

Generally speaking removing tag is not very difficult, `git` can remove both local and remote tags. Some projects delete not only tags, but whole releases in case of grievous bugs.
