### ISSUE TITLE
compatibility with GLPI 10.0.1

### ISSUE THREAD

**Issue by rafacss** [ticgal/gappessentials#32]
<p><a href="https://github.com/ticgal/gappessentials/issues/32">https://github.com/ticgal/gappessentials/issues/32</a></p><p>I'm using Gapp Ticgal 2.1 beta. When opening it asks for the Gapp Essentials plugin. I already have it installed on my Glpi in version 2.0 but I can't use Gapp TIcgal, it keeps asking to install the plugin.</p><p><br />Created by rafacss</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_10120' rel='nofollow'>10120</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by inesmv** [comment]
Hi,
we have detected the bug and we will release a new version supporting GLPI 10.0.1 as soon as possible.
Thank you for informing us.
Regards,
