### ISSUE TITLE
problème d'API de repos

### ISSUE THREAD

**Issue by basson63** [ticgal/gappessentials#34]
<p><a href="https://github.com/ticgal/gappessentials/issues/34">https://github.com/ticgal/gappessentials/issues/34</a></p><p><img src="https://user-images.githubusercontent.com/87585178/174757015-e1dc21cf-0b95-40aa-be4a-dd009b34da99.jpg" alt="Screenshot_2022-06-21-11-41-30-430_gal tic gapp selfservice" /></p><p><br />Created by basson63</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_10260' rel='nofollow'>10260</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by gitsyncuser** [comment]
<p>Hi,</p><p> </p><p>This is a misconfiguration on your GLPI or Web server. Not a software issue.</p><p>Please head here and follow the instructions:</p><p><a href=\"https://tic.gal/en/error_login_parameters_missing-connecting-to-glpi-api/\">https://tic.gal/en/error_login_parameters_missing-connecting-to-glpi-api/</a></p><p> </p><p>Regards,</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by OscarBeiro** [comment]
This is the right link:
https://tic.gal/en/error_app_token_parameters_missing-connecting-to-glpi-api/
Regards,
