### ISSUE TITLE
Does not work after upgrade to plugin 1.3.0

### ISSUE THREAD

**Issue by acmaximino** [ticgal/gappessentials#35]
<p><a href="https://github.com/ticgal/gappessentials/issues/35">https://github.com/ticgal/gappessentials/issues/35</a></p><p>After updating the app, we received a message from GAPP stating that it needs to be installed and active as per print.</p><p>It seems that GLPI is not identifying the installed plugin even though it is present, updated and active.</p><p><img src="https://user-images.githubusercontent.com/98896237/190473773-618cb966-be54-433f-8b06-e01dd9e39952.png" alt="image" /></p><p><img src="https://user-images.githubusercontent.com/98896237/190474187-ce28c169-da6d-4409-b6af-4412a30087a8.png" alt="image" /></p><p><br />Created by acmaximino</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_11162' rel='nofollow'>11162</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by PedroTicGal** [comment]
Hi @acmaximino ,

Could you tell us which version of GLPI are you trying to connect to?

Cheers.

**Comment by acmaximino** [comment]
sure, version 9.5.5. But we tried in 9.5.7 9.5.8 and 10.0.0 and receive 500 error http.

we too tried access in https://x.x.x.x/glpi/marketplace/gappessentials/apirest.php and was returned error 500 too.

**Comment by acmaximino** [comment]
Is there any specific release from our side that needs release? Access to a url to verify the registration of the marketplace, for example?

**Comment by PedroTicGal** [comment]
Hi @acmaximino,

Could you provide us your web server (ussually apache) error logs to help us to see further solutions for your problem?

Thank you.

**Comment by acmaximino** [comment]
Good afternoon, @PedroTicGal.

We are using iis as a server.

Follow the log, we tested via port 80 and 443, but it still returns error 500.

In plugin version 1.2.0 it worked normally.

[u_ex220926.log](https://github.com/ticgal/gappessentials/files/9648688/u_ex220926.log)

**Comment by PedroTicGal** [comment]
Hi @acmaximino,

This seems the connection log and, in order to help with the diagnostic of this issue, we need the error logs.

Thank you.

**Comment by PedroTicGal** [comment]
Hi @acmaximino,

We have released a new version of Gapp Essentials on the marketplace (version 2.0.2) for GLPI 10.0.3 and we expect this version to fix this issue.

Also, we are planning to release a new version of Gapp Essentials supporting GLPI 9.5.9 soon.

Could you please tell us if this new version solves this issue in your GLPI 10 instance?

Thank you.

**Comment by OscarBeiro** [comment]
Please test the last version and reopen if the issue still persists.
