### ISSUE TITLE
Gapp : Format Exception  : unexpected character (at character 1) 

### ISSUE THREAD

**Issue by 9160602200** [ticgal/gappessentials#36]
<p><a href="https://github.com/ticgal/gappessentials/issues/36">https://github.com/ticgal/gappessentials/issues/36</a></p><p>unable to login to the Gapp and getting error msg below one Error Format Exception : unexpected character (at character 1) <br />^</p><p>am using glpi 10.0.3 version</p><p><br />Created by 9160602200</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_11259' rel='nofollow'>11259</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by PedroTicGal** [comment]
Hi @9160602200,

First of all thank you for using Gapp!

I think you should see this issue from Gapp repository -> https://github.com/ticgal/gapp/issues/38

Hope it helps.

Cheers!

**Comment by PedroTicGal** [comment]
Hi @9160602200 ,
We have received your report but it seems you have trimmed it, so looks like the first step is missing. Only step 2 is present.
Could you send us the full report in order to find out which is the issue?
Cheers.

**Comment by PedroTicGal** [comment]
Hi @9160602200 ,

Could you tell us which version of Gapp Essentials do you have installed?

**Comment by gitsyncuser** [comment]
Gapp_report_2022-09-23_09:30\n\n<div dir=\"auto\"><div dir=\"auto\">Hi, </div><div dir=\"auto\"> </div><div dir=\"auto\">Am using glpi version 10.0.3</div><div dir=\"auto\"> </div><div dir=\"auto\">Gapp application  using latest version. </div><div dir=\"auto\"> </div><div dir=\"auto\">Pls check my report and unable to login into it.</div><div dir=\"auto\"> </div><div dir=\"auto\"> </div><div dir=\"auto\"> </div><div dir=\"auto\"> </div>Report generated automatically by Gapp </div><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by </blockquote>

**Comment by gitsyncuser** [comment]
Gapp_report_2022-09-23_09:32\n\n<div dir=\"auto\">Report generated automatically by Gapp </div><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by </blockquote>

**Comment by gitsyncuser** [comment]
Gapp : Format Exception  : unexpected character (at character 1) \n\n<p><a href=\"https://github.com/ticgal/gappessentials/issues/36\">https://github.com/ticgal/gappessentials/issues/36</a></p><p>unable to login to the Gapp and getting error msg below one Error Format Exception : unexpected character (at character 1) <br />^</p><p>am using glpi 10.0.3 version</p><p><br />Created by 9160602200</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by User GitSync</blockquote>

**Comment by gitsyncuser** [comment]
<p>Hi @9160602200,</p>\n<p>First of all thank you for using Gapp!</p>\n<p>I think you should see this issue from Gapp repository -> <a href=\"https://github.com/ticgal/gapp/issues/38\">https://github.com/ticgal/gapp/issues/38</a></p>\n<p>Hope it helps.</p>\n<p>Cheers!</p><br/>Created by PedroTicGal<blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by User GitSync</blockquote>

**Comment by gitsyncuser** [comment]
<p>Hi @9160602200 ,\nWe have received your report but it seems you have trimmed it, so looks like the first step is missing. Only step 2 is present.\nCould you send us the full report in order to find out which is the issue?\nCheers.</p><br/>Created by PedroTicGal<blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by User GitSync</blockquote>

**Comment by gitsyncuser** [comment]
Gapp_report_2022-09-22_16:54\n\n<div dir=\"auto\">Report generated automatically by Gapp </div><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by </blockquote>

**Comment by gitsyncuser** [comment]
<p>Ok, that is the Gapp version.</p><p>The thing I am asking for is the essentials plugin version which is installed in your GLPI.</p><p>Thank you.</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Pedro Muñoz</blockquote>

**Comment by PedroTicGal** [comment]
Hi @9160602200 ,

Could you provide us your GLPI **php** and **sql** error logs to help us to see further solutions for your problem?

![image (1)](https://user-images.githubusercontent.com/48908942/192223960-0c3f0d80-7370-4add-83a7-81a8f2de4366.png)

Also, could you answer us in the github issue instead of by email? We are making a mess in github :P

Thank you.

**Comment by veronicasmc** [comment]
Hi
I'm with the same issue.
Gapp Essentials version 1.3.0
Gapp version 2.2.0
Glpi version 9.5.7

Thanks

**Comment by 9160602200** [comment]
Still facing the same issue and waiting for solution.

**Comment by PedroTicGal** [comment]
We have released a new version of Gapp Essentials on the marketplace (version 2.0.2) for GLPI 10.0.3 and we expect this version to fix this issue.

Also, we are planning to release a new version of Gapp Essentials supporting GLPI 9.5.9 soon.

If this new version doesn't solve this issue, please reopen it.

Thank you.

**Comment by veronicasmc** [comment]
Hi, I'm in Glpi version 9.5.7. Are you planning to release a new version that can fix it for this version?

**Comment by OscarBeiro** [comment]
Possibly, but no ETA.
We are waiting for feedback from the GLPI 10 users.
Regards,

**Comment by 9160602200** [comment]
> Hi @9160602200,
> 
> We have released a new version of Gapp Essentials on the marketplace (version 2.0.2) for GLPI 10.0.3 and we expect this version to fix this issue.
> 
> Also, we are planning to release a new version of Gapp Essentials supporting GLPI 9.5.9 soon.
> 
> If this new version doesn't solve this issue, please reopen it.
> 
> Thank you.

Hi.... 

Now its Working  and  login in to the Gapp. Tq vry much....

**Comment by OscarBeiro** [comment]
Thanks for the feedback.

**Comment by veronicasmc** [comment]
I've updated to version 9.5.9 but not working yet.
Please see the error attached.
![erro gapp](https://user-images.githubusercontent.com/114772297/199710860-e8603c02-9291-418d-bd8b-1956a210e766.jpeg)
Thanks
Verônica
