### ISSUE TITLE
(GLPI 10.0.3 + glpi-gappessentials-2.0.1.tar.tgz) + GAPP 2.2.0 = ERROR API disable

### ISSUE THREAD

**Issue by mszewczy** [ticgal/gappessentials#37]
Could you please instruct the installation as it never connects to my test instance http://srvglpi.duckdns.org/glpi/?

**Comment by OscarBeiro** [comment]
Hi @Marek,

![image](https://user-images.githubusercontent.com/18396050/192210656-480a9df6-2a4e-47ff-b95c-a12d9e62cb5f.png)

You're GLPI is down. You have some trouble connecting to the DB.
This is not a Gapp Essentials issue.

Regards,
