### ISSUE TITLE
Gapp Essentials installation error

### ISSUE THREAD

**Issue by ricardo-parras** [ticgal/gappessentials#43]
Hello,

I have GLPI 10.0.6 and I tried to install Gapp Essentials from the marketplace.
Even installing through the market, after downloading, an error message appears that the app needs to be installed through the marketplace.
Other apps, even from ticgal like One-Time Secret install perfectly through the marketplace.
Can you help me about this?
![gapp](https://github.com/ticgal/gappessentials/assets/121460581/a4eb217b-d7bc-4655-9e2f-8da052ea9e2a)

**Comment by ricardo-parras** [comment]
I changed back the marketplace default location and worked.

**Comment by OscarBeiro** [comment]
Thanks for the feedback.
As stated in the Gapp manual, installing it on the marketplace folder is compulsory.
Regards,
