### ISSUE TITLE
Self-Service-Request-source - Gapp Essentials

### ISSUE THREAD

**Issue by gitsyncuser** [ticgal/gappessentials#44]
<p>Modify Essentials in order to get the \"request source\" param.</p><blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_18002' rel='nofollow'>18002</a><br>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Pedro Muñoz</blockquote>

**Comment by MikiVazquez** [comment]
Buenos días,

Tengo la versión GLPI 10.0.7 y del GAPP 2.5.0 (0000398).

Tengo múltiples orígenes de inicio de sesión. En la página de bienvenida, tengo un desplegable donde selecciono.

Sin embargo, siempre que hago login desde la aplicación, me aparece el error:

ERROR_APP_TOKEN_PARAMETERS_MISSING
The current API requires an App-Token header for using its methods.

He revisado la documentación en internet, seguida al pie de la letra, y lo único raro que observo es que dice que el valor app_token debe estar en blanco. Lo cierto es que si lo dejo en blanco y lo guardo, al recargar, aparece con otro valor.

Muchas gracias!!!
-----------

Good morning,

I have version GLPI 10.0.7 and GAPP 2.5.0 (0000398).

I have multiple login origins. On the welcome page, I have a dropdown where I select.

However, every time I log in from the application, I get the following error:

ERROR_APP_TOKEN_PARAMETERS_MISSING
The current API requires an App-Token header for using its methods.

I have reviewed the documentation on the internet, followed it to the letter, and the only strange thing I notice is that it says the app_token value should be blank. The truth is, if I leave it blank and save it, upon reloading, it appears with another value.

**Comment by OscarBeiro** [comment]
New feature on Gapp Essentials 2.2.0
