### ISSUE TITLE
Install Gapp 2.2.0 on GLPI 10.0.11

### ISSUE THREAD

**Issue by ricardo98349** [ticgal/gappessentials#46]
Unable to install App via Marketplace on GLPI 10.0.11, error Unable to download plugin file.

**Comment by OscarBeiro** [comment]
Sorry for the inconvenience.
Please test again and report back if it is not fixed.
Regards,

**Comment by ricardo98349** [comment]
Hi, it has now been installed correctly, thank you for your attention.
