### ISSUE TITLE
Parametre app_token est manquant

### ISSUE THREAD

**Issue by Mystikal57** [ticgal/gappessentials#8]
Bonjour,

Lorsque j'essai de me connecter en http, je recois un message d'erreur: "le parametre app_token est manquant; Afficher la documentation dans votre navigateur..."

une idée ?

Merci

**Comment by Mystikal57** [comment]
Au temps pour moi, j'ai enlevé la restriction d'app_token dans les paramètres d'api:

**Comment by OscarBeiro** [comment]
Désolé pour ma connaissance limitée du français

We have documented the error message here. 
https://tic.gal/en/error_app_token_parameters_missing-connecting-to-glpi-api/

Merci
