### ISSUE TITLE
Planning view, ID login and more...

### ISSUE THREAD

**Issue by M-Falken** [ticgal/gappessentials#9]
Hello,

first of all, congrats for this long awaited phone app for glpi, really great ! Keep on !

I'm testing the actual 1.0.0 connection works ok.
Just some little issues en the French translation, I will correct this.

So my first request is about that on tickets, it's always the logins that are showed.
But we need the real names at first not the login ID itself, because it's pretty useless for the techs.
Or perhaps something like "Firstname Lastname (ID login)"

And yes with the ticket list it's already very good, but a calendar view something like google calendar stuff ? Would be very nice !

Last but not list, I would like to to show a particular tab that is from another plugin, on the tickets.
So it should be a button just below the Observator field.

Feel free to tag those as enhancement.

Thanks a lot
regards

**Comment by OscarBeiro** [comment]
Hi @M-Falken,
Thanks for testing Gapp.
Regarding your concerns:

1. We are discussing this and will be added to the roadmap. Main problem is a lack of space to add the huge amount of information available in GLPI. We'll deal with this in the future.

1. Another great idea, but this is one is too early to get to it. 

1. The last one is difficult to understand. What plugin are you talking about? 

If you wish to sponsor any dev, please contact us.

À bientôt :)

**Comment by M-Falken** [comment]
Thanks for reply

Ok for 1.
The names instead of the IDs, I can tell that on my phone the fields spaces are wide enough to put the complete names instead of the IDs.

Ok for the 2.

For the 3.
The plugin is the https://github.com/JulioAugustoS/glpi-orderservice/releases
(You can try it to see how it deals with the ticket page)
But since I've tweaked it a lot for my own use.
Anyway this one put a particular tab on the left of the ticket page.
Then when we click this tab and so the page shows a button that we can click too, this one lead us to the "intervention sheet" just like below.
![screenshot-2019 09 25-17_02_36](https://user-images.githubusercontent.com/1380639/65613967-1bcdeb80-dfb7-11e9-97e2-4e3c60a88171.png)

Regards

**Comment by OscarBeiro** [comment]
Hi again,
Sorry about the delay. We were finishing the new release :)
1.  This particular area is going to change as soon as we confirm our last release is stable.

1.  :)

1. One of the ideas behind Gapp is going paperless. I don't think your request fits in the roadmap. As stated before, we can make a custom development if needed.

I forgot to thank you for your French translation offering. We are currently using poeditor, I don't know if we stay for long, but right now is the best we have.

Please, feel free to join the project and correct our errors in French: https://poeditor.com/join/project/N26O1x7Nd5

Merci

**Comment by M-Falken** [comment]
Hi
As you've seen, I'm now on the French translation, will finish it asap.

Yes for us too, we try to reach the zero paper, but in this case I just need to access the page from the button, and the goal is to let the customer sign by hand on the smartphone.
So next step is to have a "sign zone by hand" for the solution approval.

And a little thing about the ticket description field on the app, the high is too big and so there's a big empty white space, perhaps an auto height with a min-height stuff would be better.

Regards

**Comment by OscarBeiro** [comment]
Thanks for the corrected translation, we will release soon.

I understand your needs, but as I told you before,  something that specific must be developed. and it should be funded.

Regards

**Comment by OscarBeiro** [comment]
100% French translation has been added to last Gapp version.
We'll keep this repository to Gapp Essentials issues.
Please post your Gapp issues at https://github.com/ticgal/gapp 

Merci ;)
